### ISSUE TITLE
Error page guidance

### ISSUE THREAD

**Issue by christaylor-hod** [UKHomeOffice/design-system#100]
## The need the pattern/component meets 
We have noticed that users are using contact methods like twitter to tell us that there are problems with services. We feel that with better guidance and reassurance on error pages we may be able to reduce the need to contact us.

@charlesrt suggested that the standard error page needs to convey:

Plain language — no-one cares about a 500 server error
Direction content — how to get back to what you were doing, or get to where you might want to go
Help — doesn't have to be a specific telephone number, especially as sometimes the error might be a bit random, but should contain some way of finding out how to find help, or contact someone for help if needed.

## Why you think it should be included in the design system 
We think having consistent guidance on what to include in error pages will help to reduce the amount of enquiries from users. 

## Example screenshots from your service or others  
HMRC already have a pattern around this that we could base ours on: http://hmrc-design-language-prototype.herokuapp.com/design-patterns/patterns/pages/500_page/500-alternative-channel.png

## Any user research  
Need to do some research around this. @karypun is looking at implementing the HMRC version.

**Comment by christaylor-hod** [comment]
@owenm6 can you add a label to this? I cant figure out how

**Comment by martinwake** [comment]
Some starting points:

Service manual discussion paper https://paper.dropbox.com/doc/Untitled-icpXYcakR5K9B6DfU5R8d

HMRC guidance http://hmrc-design-language-prototype.herokuapp.com/design-patterns/patterns/pages/404_pages/

Home Office copy checked by the team https://github.com/UKHomeOffice/docker-nginx-proxy-govuk/tree/master/html/partials

Copy used on GOV.UK https://github.com/alphagov/static/tree/master/app/views/root

**Comment by martinwake** [comment]
Is this specifically for a 500 error or shall we make guidance for all HTTP status codes? I think it would be useful but might be extending the scope too far.

**Comment by owenm6** [comment]
https://home-office-digital-patterns.herokuapp.com/patterns/error-pages

**Comment by owenm6** [comment]
Closed and removed from the system. This is covered by the GOV.UK Design system.

[Page not found (404)](https://design-system.service.gov.uk/patterns/page-not-found-pages/)
[Problem with page (500)](https://design-system.service.gov.uk/patterns/problem-with-the-service-pages/)
[Service unavailable](https://design-system.service.gov.uk/patterns/service-unavailable-pages/)
