### ISSUE TITLE
Enquiry form

### ISSUE THREAD

**Issue by martinwake** [UKHomeOffice/design-system#101]
A basic form for submitting enquiries. May include options for what an enquiry is about and for specifying contact preferences, etc.

**Comment by owenm6** [comment]
@martinwake Have you got any good examples?

**Comment by martinwake** [comment]
@owenm6 I think the example is good. Do you have any thoughts on whether it would be worth:
- mentioning that we might ask the subject of their enquiry (eg selecting from a list)
- including some information about where this information might go to (eg a database, an email to a customer resolution team)

**Comment by owenm6** [comment]
@martinwake Yes to both these suggestions. Thanks

**Comment by owenm6** [comment]
Pattern live - https://home-office-digital-patterns.herokuapp.com/patterns/enquiry

**Comment by karypun** [comment]
Closing this issue as it currently exists in the design system. Raise a new issue if needed.
