### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#102]
An alert component - for persistent alerts in internal services
 
## The need the pattern/component meets 
Tells the user something new has happened, or confirms an action

## Why you think it should be included in the design system 
A lot of services are already using notifications

**Comment by owenm6** [comment]
https://home-office-digital-patterns.herokuapp.com/components/alerts

**Comment by karypun** [comment]
Closing this issue as it currently exists in the design system. Raise a new issue if needed.
