### ISSUE TITLE
Accessing help in-service

### ISSUE THREAD

**Issue by simon-castillo** [UKHomeOffice/design-system#104]
## The need the pattern/component meets 
In Right to Work (a public service) user research sessions, participants did not see where to find help information, despite links being displayed in context and a 'help' link in the grey footer.

## Why you think it should be included in the design system 
In-service help links are inconsistent across public services on GOV.uk. The link in the grey footer suggests help with GOV.uk as a whole – which it is when you are on the main site – but many services change it to link to in-service help. A consistent, noticeable location for help will guide users to the right information and prevent wasted clicks.

## Example screenshots from your service or others  
![image](https://user-images.githubusercontent.com/24433505/40772860-0c430490-64b9-11e8-92c7-6a2959f9cf52.png)

## Any user research  
Currently prototyped, to be tested in next rounds of research.

**Comment by owenm6** [comment]
@simon-castillo Would be good to know the type of help users need. And how often users require help.

**Comment by simon-castillo** [comment]
@owenm6 For us that links to a page with: contact details for assisted digital help and general enquiries, guidance on what to do if we're displaying their information incorrectly (this guidance is also displayed in context), and routes to other services if the user realises their situation doesn't apply to our one.

We don't have an estimate for how often users need help, but this stemmed from asking user research participants what they would do when they are unsure, or have a question, which happens in most sessions.

**Comment by owenm6** [comment]
https://www.gov.uk/service-manual/helping-people-to-use-your-service/set-up-and-manage-user-support

**Comment by owenm6** [comment]
@simon-castillo Any further developments on this pattern?

**Comment by simon-castillo** [comment]
@owenm6 we've taken this out to test a few times and most users have not noticed it - despite having questions, they either go through the service anyway or say they would call a number that they already have.

The pattern has been built in the live service as it was our best assumption of where a general help link could go, but we're keeping an eye on analytics to see how many clicks it receives vs. the link in the footer, and continuing to test it in the prototype. Next options might be to bring it out of the blue line or move it to the top of the page.
