### ISSUE TITLE
Illustration style for guidance

### ISSUE THREAD

**Issue by eliothill** [UKHomeOffice/design-system#105]
Illustrations are being used in HMPO, Digital Status and other UKVI services to communicate often hard to describe actions users need to take or where to find information they need to provide.

They have been well received by users in reassuring what they are doing and what information they are providing. 
 
## The need the pattern/component meets 
Illustrations have been working but the style, need and application of the illustrations varies dramatically and having guidance. 

## Why you think it should be included in the design system 
Demonstrating best practice for their use and examples would help teams identify if it's appropriate for their service and how to use them.

## Any user research  
Users who have dyslexia have expressed in one service how they have relied almost entirely on the image to understand what they needed to do.

In UKVI services where lower language skills are more prevalent, users have express reassurance from seeing the image that the data they are entering is the correct one – in particular BRP cards.

**Comment by owenm6** [comment]
@eliothill We have this in our central team backlog as part of the ongoing styling work. Will get it bumped up in priority.

**Comment by owenm6** [comment]
Draft guidance here - https://ho-design-system-test.herokuapp.com/style_guide/images

**Comment by catrionabudge** [comment]
Duplicate, info already somewhere else
