### ISSUE TITLE
Focus state of inverted button

### ISSUE THREAD

**Issue by dashouse** [UKHomeOffice/design-system#107]
The focus state of the inverted button goes back to the default button background colour.

<img width="212" alt="screen shot 2019-03-01 at 14 14 31" src="https://user-images.githubusercontent.com/23356842/53643745-bab28500-3c2c-11e9-98e4-6579702dd901.png">

**Comment by owenm6** [comment]
Oh dear. Thanks for highlighting @dashouse. I'll fix it.

**Comment by owenm6** [comment]
All fixed with the latest commit.
