### ISSUE TITLE
Side tab CSS is outdated and won't work

### ISSUE THREAD

**Issue by zuzak** [UKHomeOffice/design-system#108]
The CSS example for the [side tab element](https://home-office-digital-patterns.herokuapp.com/components/side-tab) (#97) doesn't work with the HTML given.

The CSS the design system website actually uses is in [app/assets/sass/components/_side-menu.scss](https://github.com/UKHomeOffice/design-system/blob/8146c38a10a65ee9e74a2e253a056eeef1c15be6/app/assets/sass/components/_side-menu.scss) which uses `ul.tab__nav` as the selector.

The CSS the design system tells you to use is in [app/views/includes/css/tab.scss](https://github.com/UKHomeOffice/design-system/blob/2fb5552fb53498f3e66ebf53377835c28323fdee/app/views/includes/css/tab.scss) which uses `.tabs` as the selector. As that doesn't appear anywhere in the HTML, it won't work.

----

This happened because the examples and the actual code used is duplicated in two different locations, so it's easy for them to accidentally diverge.

The GDS GOV.UK Design System seems to gets around this problem by only defining each component once, and using itself to generate the component examples. Perhaps we should delete the `views/includes` directory and instead generate examples directly from the `assets/sass` folder (or vice versa).

**Comment by owenm6** [comment]
Thanks @zuzak for pointing out the mistake in the snippets. These should be fixed now. 

The bigger issue of showing CSS snippets will take a bit more work. We used to pull them straight from the component but since switching to a govuk frontend we haven't been able to do that.

**Comment by zuzak** [comment]
Most (all?) of the other CSS snippets hardcode colours (e.g. `color: #0B0C0C`) but the snippet introduced in de2a93a refers to the SASS variables (e.g. `color: $black`). Is that intentional?

**Comment by owenm6** [comment]
@zuzak No not intentional. We remove colour variables from snippets as they don't add value and can cause issues. In my rush to fix the issue I forgot to take them out.
