### ISSUE TITLE
What format/design to use if a profile photo is not available

### ISSUE THREAD

**Issue by SueSpevack** [UKHomeOffice/design-system#114]
Have had a number of requests of what to use if a profile photo isn't available - should it be an avatar or some other graphic element or not an image placeholder at all.

**Comment by cocoforbes** [comment]
Example of department crest being used by MOJ![49813375-410ea780-fd5f-11e8-8d45-df63f7d40547](https://user-images.githubusercontent.com/47001925/60811914-2cc14a80-a188-11e9-8b72-61757ad32ebe.png)

**Comment by helenadt** [comment]
Example of crest being used in an MOJ service.

![49813375-410ea780-fd5f-11e8-8d45-df63f7d40547](https://user-images.githubusercontent.com/25151199/60812357-339c8d00-a189-11e9-9034-415e52caa3b9.png)

**Comment by SueSpevack** [comment]
Closing and moving this issue to here: https://github.com/UKHomeOffice/design-system/issues/154
