### ISSUE TITLE
2FA Using Email Verification

### ISSUE THREAD

**Issue by sulthan-ahmed** [UKHomeOffice/design-system#118]
## What
Update the guidance for securely identifying users through the use of the Email. https://home-office-digital-patterns.herokuapp.com/patterns/identifying-users

GDS have approved our design for email verification.  Note: we have not yet completed our user testing

### Our Design
If using email for quasi-two-factor authentication make it a tokenised link, not a code that people have to copy/paste.

we enable the link to be used multiple times, but expire it when the user clicks the Start button

## Why
> - What evidence do you have that it's needed?
GDS have highlighted the need as have we for the report modern slavery service
https://www.modernslavery.homeoffice.gov.uk/start

> - What evidence do you have that it meets the needs of the users of Home Office services?
We have carried out user research as have GDS

> - Have you checked that it doesn't already exist in the GOV.UK Design System or Home Office Design System? 
Yes

## Anything else

You can follow our discussion here
https://github.com/alphagov/govuk-design-system-backlog/issues/25

**Comment by sulthan-ahmed** [comment]
we have conducted user testing it has gone well, we are hoping to release it on Thursday

**Comment by karypun** [comment]
Already raised on GDS; needs more information.

**Comment by sulthan-ahmed** [comment]
Hi @karypun would it be possible to talk about this?  GDS have approved the design.  I've also written a blog about it which has been well received across government.  I agreed with @christaylor-hod to raise it here so that it could start discussion to be put in the design system.  Happy to share the blog which has more information
