### ISSUE TITLE
Archive the previous iterations

### ISSUE THREAD

**Issue by chrisns** [UKHomeOffice/design-system#122]
On our github we have a few repos including but not limited to (searched for design)
https://github.com/UKHomeOffice/home_office_design_kit
https://github.com/UKHomeOffice/design-patterns

If this is now the canonical truth can we write something in the README.md of those repos to either direct them here and then archive them, or explain how they fit into the bigger picture and are still relevant?

**Comment by ctdesign** [comment]
@chrisns they are all different things

home_office_design_kit is a fork of the Gov.UK prototype kit with additional styling for internal Home Office systems

design-patterns is a repo for a sketch template, which allows designers to design layouts in the Sketch mac software. 

I'll look into expanding the readmes to make this clearer, but they are both relevant repos that are used.
