### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by SueSpevack** [UKHomeOffice/design-system#155]
## What
 A set of icons with guidance on how and when to use them.

## Why
The previous icon set was inconsistent and not widely used, There is a need from designers for certain icons, especially in internal services.

## Anything else
If you've used icons in your service and seen them tested with users, please add your experiences in the comments below.

**Comment by joeedhorton** [comment]
I've always imagined icons to be under styles rather than components. Or at least not under components. They seem like a foundational element?

**Comment by SueSpevack** [comment]
Blog written in regards to icons and relevant information on how they used and why: https://hodigital.blog.gov.uk/2017/08/18/good-icons-should-be-invisible/

**Comment by tomyems** [comment]
The current Home Office Design System does not have icons. If there is a future need for icons or you found them useful, create a discussion.
