### ISSUE TITLE
Status banner 

### ISSUE THREAD

**Issue by joeedhorton** [UKHomeOffice/design-system#157]
## What
Help users understand the status of something, so they know what to do next.

## Why
There are multiple services, mostly internal caseworking services that show the status of a case. However, there are multiple styles used and it would be useful to have guidance and examples.

## Discuss
If you've shown users the status of something in your service and seen them tested with users, please add your experiences in the comments below.

![status](https://user-images.githubusercontent.com/55453490/86223525-8da71700-bb7f-11ea-8733-66a28e27fbad.png)

## Related to:
[GOV.UK Design System backlog issue](https://github.com/alphagov/govuk-design-system-backlog/issues/98)

**Comment by RobinKnipe** [comment]
Component package: https://github.com/UKHomeOffice/design-system/tree/master/components/status-message
