### ISSUE TITLE
Typography

### ISSUE THREAD

**Issue by joeedhorton** [UKHomeOffice/design-system#158]
## What
Typography scale for internal Home Office services.

## Why
The current typographic scale lacks depth in its scale and needs to be reviewed to ensure it is meeting the needs of the designers internal services. 

## Discuss
If you've improved, added or adapted the typography scale for an internal service, please add your experiences in the comments below.

### Current guidance
[Home Office Design System — Typography](https://design.homeoffice.gov.uk/styles/typography)

**Comment by karypun** [comment]
We are now using a new typeface, replacing Inter with Roboto for better inter-operability with GOV.UK design components.
