### ISSUE TITLE
Navigation content hidden on narrow viewports 

### ISSUE THREAD

**Issue by charlesrt** [UKHomeOffice/design-system#161]
When viewing the Design System manual on a narrow viewport, like a mobile device, the navigation items that appear on in the sidebar on wider viewports are hidden behind an action labelled, ‘Menu’. 

This can give the impression once navigating to a new section that there is nothing there. 

Might it work better if the navigation content continues below the main body content?

**Comment by joeedhorton** [comment]
Hi @charlesrt, I've asked Arslan for some stats around the devices used, so we can see the breakdown of mobile/tablet/desktop visits. I think from there, we could get a an idea of where this sits in our priorities at the moment and judge whether it needs to be addressed sooner or later.

Will keep you updated.

**Comment by joeedhorton** [comment]
Hi @charlesrt, Desktop has the majority, with mobile being a very few so I am putting this into the _To do_ list to be completed in a future sprint as I don't think it should take priority over other issues at the moment. 

<img width="587" alt="Screenshot 2020-07-08 08 50 32" src="https://user-images.githubusercontent.com/55453490/86899263-b2603900-c101-11ea-9505-72f54cb1745e.png">

**Comment by joeedhorton** [comment]
Designs are done, waiting for a developer to take it onboard as we step into complicated javascript territory. 

https://www.figma.com/file/zilewk3BPK8HzGkOTk4FuY/mobile-screens-home-office-design-system?node-id=0%3A1

**Comment by karypun** [comment]
This issue pertains to the old design system. Will close this
