### ISSUE TITLE
Accessibility on "check and confirm details"

### ISSUE THREAD

**Issue by manalishi79** [UKHomeOffice/design-system#166]
## What
Currently the ["check and confirm details"](https://design.homeoffice.gov.uk/patterns/check-and-confirm-details) component recommends an overlay to confirm the information. Overlay popups are said to be problematic for accessibility. Is there another way the desired outcome could be achieved using something less troublesome for accessibility.

## Why
Makes the component more accessible. Removing dependency on JS/CSS tricks or bloated code will make are services leaner less fragile to maintain.

**Comment by joeedhorton** [comment]
Hi @manalishi79, have you come across any examples in Immigration that you could share that take a different approach?

**Comment by joeedhorton** [comment]
Closing this issue as it has been inactive for 30 days. 
This issue will be re-opened if we begin work on researching alternatives. 

Comment and share if you have examples that take a different approach than the 'modal' in this pattern.

**Comment by joelanman** [comment]
it looks very similar to this pattern:
https://designnotes.blog.gov.uk/2015/09/15/make-sure-this-is-right-a-new-email-confirmation-pattern/
which just uses a page instead of a dialog. @manalishi79 is right, dialogs can cause accessibility issues and require javascript, so a page is often simpler and more accessible

**Comment by joeedhorton** [comment]
Great find @joelanman! Am I right in thinking you worked on the this project? Would be great if you had research findings that you could share 👍

**Comment by joelanman** [comment]
I did yeh, only the info in the blog post I'm afraid, though I might be able to dig something up from the [Coronavirus Shielded People Service](https://www.gov.uk/coronavirus-extremely-vulnerable) where we also used it
