### ISSUE TITLE
Error: I get a 'found 11 vulnerabilities (4 low, 1 moderate, 6 high)' flag when I run npm install

### ISSUE THREAD

**Issue by IxDbloke** [UKHomeOffice/design-system#171]
Hi, hope this is the correct place for bug fixes. I downloaded the zip file, opened it in a 'Projects' folder and ran npm install. I then ran npm audit fix and got the following error message. Thanks

found 11 vulnerabilities (4 low, 1 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details
admin@hodaccadms-MBP design-system-master **% npm audit fix**
npm ERR! code EAUDITNOLOCK
npm ERR! audit Neither npm-shrinkwrap.json nor package-lock.json found: Cannot audit a project without a lockfile
npm ERR! audit Try creating one first with: npm i --package-lock-only

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/admin/.npm/_logs/2020-08-12T13_33_32_750Z-debug.log

**Comment by joeedhorton** [comment]
I get similar vulnerabilities @IxDbloke, but the prototype and local host still works for me. How about you? 

We are working on building a new prototyping kit from the ground up (in react)... so will keep you updated on that. In the meantime, you might be able to hear about any updates on this new kit from Daniel Martin (our tech lead) in our monthly meet-ups or in the Home Office Design System slack channel.

**Comment by daniel-ac-martin** [comment]
In terms of this prototyping kit, it's worth bearing in mind that it is not suitable for production. As long as you aren't putting any sensitive data through it I wouldn't worry too much about those vulnerabilities.

**Comment by IxDbloke** [comment]
OK thanks, yes I'm really doing this to create a disposable prototyping kit and establish good design patterns, it won't go near production.
________________________________

**Comment by karypun** [comment]
Will close this as there will be vulnerabilities provided they don't affect your ability to run the prototype. If it does, do feel free to raise this again.

**Comment by IxDbloke** [comment]
Thanks Karwai
________________________________
