### ISSUE TITLE
Tags (currently called labels in the HO design system)

### ISSUE THREAD

**Issue by isobelseacombe** [UKHomeOffice/design-system#213]
I've done a bit of comparison of the different tags that are in use in gov and NHS. The rules for usage from the NHS are pretty sound so I've been following them. https://service-manual.nhs.uk/design-system/components/tag

![Tags](https://user-images.githubusercontent.com/43995752/116562566-2c64e700-a8fb-11eb-8ddf-ad009ce8c638.png)

### Thoughts on the differences in design:
In terms of contrast against the grey background, the ones with the stroke around them are much more visible. 

The boxes around the gov ones are quite large - so when using them in tables they could do with being a bit smaller.  

### Use cases for them so far:

Using them to show a binary status of a thing: 
- a report being complete/incomplete 
- an item of reference data showing as active/inactive

Multiple statuses that change over a period of time - to show when a record is coming towards its expiry date and requires action to be taken. 

<img width="486" alt="status tags in a table" src="https://user-images.githubusercontent.com/43995752/116564207-aba6ea80-a8fc-11eb-88cf-32153cbafd2f.png">

### Usability testing
Obviously we shouldn't rely on colour as the only way of displaying information - but it does help to support the understanding of the status. In this case (screenshot above) it was noted in usability testing that the user liked the 'traffic light' colours for each of the statuses and it helped them to understand which one to action first. This is something that has come up in previous policing projects and seems to be a theme used across other police IT.

**Comment by karypun** [comment]
Hi @isobelseacombe I'm going to close this issue as we have it captured with more input in 
https://github.com/UKHomeOffice/design-system/issues/43
