### ISSUE TITLE
Components should not depend on configuration objects

### ISSUE THREAD

**Issue by bertrandmc** [UKHomeOffice/design-system#232]
Hi,

Thanks so much for this project, we are looking forward to integrating it in the XGovFormBuilder project.

I have had a look at the components created so far and I would like to raise an issue with their design.

React components are best if they are written in a way that, on the user-land, we can consume and build the interface as pure JSX instead of passing configuration via objects, there are several reasons for this but the most important is to make components easy to extend and customize for different use-cases without need to implement and document APIs. 

Below I am giving an example using the footer. 

ATM this is how I can write the footer with navigation. 

```javascript
import { Footer } from "@hods"

return (
  <Footer
    navigation={[
      {
        href: "/feedback",
        text: "Feedback",
      },
      {
        href: "/help",
        text: "Help",
      },
      {
        href: "https://gov.uk/",
        text: "Gov.UK home",
      },
    ]}
  />
)
```

As a user, if I needed to give some prop to one of the menus, let's say a className or a test-id, the component have to expose that API via the configuration object and I will have to be diving into the documentation to make sure it does, otherwise I can't extend it, also, if I want to handle some UI condition, let's say hide one of the menus based on some criteria, I have work on the object/JS instead of JSX, so the design is limiting the tools I have. 

Ideally, this is how I would like to write the component in JSX:

```javascript
import { Footer } from "@hods";

const { enableFeedback } = props;
const { Navigation } = Footer;


return (
  <Footer>
    { enableFeedback && <Navigation href="/feedback" data-test-id="123">Feedback</Navigation> }
    <Navigation href="/help" className="active">Help</Navigation>
    <Navigation href="https://gov.uk/">Gov.UK home</Navigation>
    <ApplicationVersion />
  <Footer>
)

```
Because passing props to a component is the expected behaviour, I don't need to remember what the navigation list should look like nor go through documentation, I just pass the props I need and job done, from your side, there is no need to implement/handle that via the configuration object nor write documentation for it.

**Comment by daniel-ac-martin** [comment]
@penx:  Sorry, I've been meaning to sit down and write a proper reply for ages.

We do still have a repo that is using govuk-react at https://github.com/UKHomeOffice/lev-react-components . It's a bit unloved though. (@aarongill1 will know more about it than me.)

Thanks for the offer of a call. It would be nice if a few of us started discussing ideas around best practices with React and also these component libraries and how to maintain them.

At the moment we've got some duplication of effort. Which looks quite bad on the surface, but is ultimately the result of us having different opinions on the best way to go about this stuff (and slightly different goals!). If we start talking some more we might come to common understanding that would allow us to concentrate our efforts.

In the meantime maybe we could have a slack channel on X-Gov or some other text-based communication?

**Comment by penx** [comment]
> At the moment we've got some duplication of effort. Which looks quite bad on the surface, but is ultimately the result of us having different opinions on the best way to go about this stuff (and slightly different goals!). If we start talking some more we might come to common understanding that would allow us to concentrate our efforts.

Your NotGovUK library looks good, and has some patterns in it that I was planning to be in govuk-react at some point. But we haven't had too many people get in touch with us about usage, issues, architectural suggestions etc. so it's hard to prioritise. I think we may find we're more aligned than you think, it's just that govuk-react isn't quite where we want it to be yet.

> In the meantime maybe we could have a slack channel on X-Gov or some other text-based communication?

Unfortunately I'm not on the X-Gov slack anymore, but yes lets find a way to DM each other first and then figure out a slack channel or similar for wider discussion. I'm on Twitter at https://twitter.com/penx and you should be able to find me on LinkedIn (I think I sent you a request yesterday, assuming I found the right person!)
