### ISSUE TITLE
Accessibility issue 3 - text size of code lines too small

### ISSUE THREAD

**Issue by karypun** [UKHomeOffice/design-system#257]
Pages affected: [Starting a new prototype](https://design.homeoffice.gov.uk/get-started/start-prototype) and [Building your prototype](https://design.homeoffice.gov.uk/get-started/use-prototype)
Issue: Text size of code lines is smaller than other text on the page - may not be a standard size
Resolution: Make them standard size

**Comment by daniel-ac-martin** [comment]
For now, we should probably add some SCSS code to `app.scss` to re-style this.

**Comment by haggishunt56** [comment]
Have added
```
code{
  @include govuk-font(19);
  font-family: Courier, Consolas, serif;
}
```
to app.scss

**Comment by daniel-ac-martin** [comment]
This should be fixed now.

**Comment by haggishunt56** [comment]
@MarionDownie can this issue be closed now?

**Comment by MarionDownie** [comment]
Yes, looks fine to me.
