### ISSUE TITLE
Accessibility issue 5 - address footer content reflows correctly

### ISSUE THREAD

**Issue by karypun** [UKHomeOffice/design-system#259]
Pages affected: all pages
Issue: The footer didn't reflow very well and required horizontal scrolling at 400% (Edge 90, Chrome 91) and on mobile (Android 11/Chrome 91, iOS 13.7/Safari). There were also issues with the main content overlapping the footer on IE 11.
Resolution: Ensure that footer content correctly reflows and does not obscure main content with a browser zoom of up to 400%, on mobile and IE 11

**Comment by haggishunt56** [comment]
Have added a flex-wrap property to these elements and tested with multiple resolutions and zoom levels (though not on multiple browsers). Pull request created.
