### ISSUE TITLE
Accessibility issue 6 - divide site map into relevant sections

### ISSUE THREAD

**Issue by karypun** [UKHomeOffice/design-system#260]
Pages affected: [Site map](https://design.homeoffice.gov.uk/sitemap)
Issue: Would recommend that the site map is divided into the relevant sections. A good example is: https://www.w3.org/WAI/sitemap/
Resolution: Divide site map into the sections that those pages are found on through the main navigation

**Comment by haggishunt56** [comment]
@MarionDownie can this issue be closed now?
