### ISSUE TITLE
Accessibility issue 7 - parsing issue

### ISSUE THREAD

**Issue by karypun** [UKHomeOffice/design-system#261]
Pages affected: [Component header page](https://design.homeoffice.gov.uk/components?name=Header)
Issue: Under 4.1.2: Name, Role, Value there is a parsing issue of attribute src not allowed on element image at this point. That's in the SVG element on the Component - Header page.
Resolution: Remedy incorrect src usage on the <image> element.

**Comment by daniel-ac-martin** [comment]
I wonder if this has since been fixed. - I can't find the problem: https://validator.w3.org/nu/?doc=https%3A%2F%2Fdesign.homeoffice.gov.uk%2Fcomponents%3Fname%3DHeader

**Comment by daniel-ac-martin** [comment]
We think this is fixed.
