### ISSUE TITLE
Accessibility issue 8 - ensure screenreader reads out link text 

### ISSUE THREAD

**Issue by karypun** [UKHomeOffice/design-system#262]
Pages affected: all?

Issue: Strange issue with JAWS 2019 on Edge Version 90.0.818.41 - when tabbing through links, visible headings from main page were always announced before the link. For example on the Access a service patter JAWS read out: Help users to Access a service, When to use this pattern, Access a service with identity documents, Access a service link.

Resolution: Ensure that when a screen reader user navigates the page, both with a tab key and by reading the page, that only the link text is read out

**Comment by guermanc** [comment]
Agreed that this was a JAWS specific issue.
