### ISSUE TITLE
Update notifications

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#30]
Notifications that a product has been updated

**Comment by christaylor-hod** [comment]
Seems like HODAC, Proving Things and SIP are using a variant of this.

To do:
Collect screenshots of the versions and investigate further

**Comment by chris-hanson-hoddat** [comment]
<img width="991" alt="screen shot 2017-10-05 at 14 09 38" src="https://user-images.githubusercontent.com/22620603/31228866-d7d23bba-a9d6-11e7-95ea-c277df0c4d31.png">

**Comment by owenm6** [comment]
From talking with designers on service teams, telling users about a lot of new features doesn't work. Staff are too busy and don't read the updates. Might be better to focus on telling the user about one new feature.
