### ISSUE TITLE
unable to use Docker file in apps

### ISSUE THREAD

**Issue by drrcodebase** [UKHomeOffice/design-system#314]
Docker file present in apps not working

**Comment by daniel-ac-martin** [comment]
HI @drrcodebase. Are you able to provide any more information? Are you getting any error messages?

**Comment by drrcodebase** [comment]
is there any `readme` file to run the docker image . I run the following commands to run the application in docker container.  application is not up and running .

Inside  apps>docs > folder I runt he following two commands 

Docker build -t react-image .
Docker run -d -p 3000:3000 --name react-app react-image

**Comment by daniel-ac-martin** [comment]
@drrcodebase: Did you build the application first? (`npm run build`)

Alternatively, I think there should be a makefile that you can use with `make docker`.

**Comment by drrcodebase** [comment]
Thanks @daniel-ac-martin  , it works now .
