### ISSUE TITLE
Confirm input

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#32]
Confirm user inputs like email addresses and other important data that the user can't go back and amend

<img width="418" alt="screen_shot_2017-09-04_at_09 58 14" src="https://user-images.githubusercontent.com/13904084/30317772-0d948c3a-97a3-11e7-93f4-aab29061632b.png">
<img width="660" alt="screen_shot_2017-09-04_at_09 58 27" src="https://user-images.githubusercontent.com/13904084/30317774-0ebe8d18-97a3-11e7-86b5-4f81ebd15830.png">
<img width="686" alt="screen_shot_2017-09-04_at_09 57 45" src="https://user-images.githubusercontent.com/13904084/30317777-1022af04-97a3-11e7-8d48-baa98b7f65d6.png">
<img width="891" alt="screen_shot_2017-09-04_at_10 38 07" src="https://user-images.githubusercontent.com/13904084/30317780-11974fca-97a3-11e7-9e40-a717fef91061.png">

**Comment by eliothill** [comment]
Updated content on [confirmation branch](https://github.com/UKHomeOffice/home-office-digital-patterns/tree/confirmation)

**Comment by martinwake** [comment]
I've just updated a content-reviewed version. One thought: could "Confirmation" be confused with the final screen of the loop? On projects that's often casually called "the confirm screen" and I've in the past used things like "Verify" or "Check" for the previous screen. 

Perhaps the whole pattern is "Check and confirm"?

**Comment by owenm6** [comment]
I agree that Check and confirm is more descriptive and less confusing then simply calling it a confirmation pattern

**Comment by eliothill** [comment]
@martinwake can you review the content in the imagery of the pattern as well? Conscious you can't change it so let me know and I can update.

**Comment by martinwake** [comment]
@eliothill The change I mentioned to Mike (apostrophe) was the only change I could see that was needed

**Comment by catrionabudge** [comment]
Links to this issue in gov.uk backlog https://github.com/alphagov/govuk-design-system-backlog/issues/9

**Comment by matthew20177** [comment]
Her

**Comment by matthew20177** [comment]
Help me

**Comment by matthew20177** [comment]
Help me

**Comment by matthew20177** [comment]
Hey
