### ISSUE TITLE
Uploading a file

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#33]
A pattern for uploading files (single or multiple) to an internal service.

## Examples in the Home Office

![passport_renewal](https://user-images.githubusercontent.com/13904084/30317978-b571f73a-97a3-11e7-880f-54e665dd649b.gif)  

![evw](https://user-images.githubusercontent.com/13904084/30317988-ba071a8c-97a3-11e7-82ce-4f8f3a0d843a.gif)  

![firearms](https://user-images.githubusercontent.com/13904084/30317991-bba2af82-97a3-11e7-9957-46abf76eac35.gif)

**Comment by owenm6** [comment]
Initial commit of pattern 97ec2cda49de688bd0646435140063c0e17b7ec9

**Comment by owenm6** [comment]
Need to also look at:

* enhancing with drag and drop
* handling errors on upload - probably on step 3

**Comment by martinwake** [comment]
We have conflicting anecdotal reports of whether the word "upload" has tested well or poorly with users vs "add". I'd like to review the evidence before we recommend using or avoiding either.

**Comment by catrionabudge** [comment]
Closed as pattern published on gov design system which is mostly the same, pattern for multiple uploads covered by #36
