### ISSUE TITLE
Identifying users

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#34]
Might be handled by Key Cloak but would be good to have a recommended way of users signing in. 

## Examples
https://paper.dropbox.com/doc/68O9bdpgCixU42XEqWoCK

**Comment by christaylor-hod** [comment]
Maybe include some specific keycloak guidance

**Comment by christaylor-hod** [comment]
Maybe this is something that the centre of excellence could help coordinate

**Comment by helenadt** [comment]
![sign in - book travel in and out of the uk](https://user-images.githubusercontent.com/25151199/32658742-605e32b0-c613-11e7-8c0f-ec773c8b3a30.png)

This is the sign in page from 'Book travel in and out of the UK'. We had to create a new Keycloak template so we could use gov styles. This template should be available for others to use if going though the Home Office the DSP hosting platform.

**Comment by owenm6** [comment]
I've added a draft of this pattern - https://home-office-digital-patterns.herokuapp.com/patterns/identifying-users

**Comment by SueSpevack** [comment]
This pattern is now called Access a service https://design.homeoffice.gov.uk/patterns/access-a-service

Closing this issue as it currently exists in the design system. Raise a new issue if needed
