### ISSUE TITLE
Pagination should be functional

### ISSUE THREAD

**Issue by daniel-ac-martin** [UKHomeOffice/design-system#340]
The [Pagination component](https://design.homeoffice.gov.uk/components?name=Pagination) should be updated so that it is functional.

It should probably take children and display a set number of them at any one time. e.g.

```jsx
<Pagination itemsPerPage={5}>
  <Item>[...]</Item>
  <Item>[...]</Item>
  <Item>[...]</Item>
  <Item>[...]</Item>
  <Item>[...]</Item>
  <Item>[...]</Item>
  <Item>[...]</Item>
  <Item>[...]</Item>
</Pagination>
```

Instead of the children we could take an `items` prop, I'm not sure if there is a benefit though.
The current page could be taken from the query string, with the `useLocation` hook.

Further down the line we could do something like only fetch the items we need to display the current page.

**Comment by MikeDThorpe** [comment]
Is it necessary for the pagination component to reload the page when loading new data? Is this considered a better practice than a hot reload from a design perspective as the url shows the details of the current page? i.e ?page=3

**Comment by daniel-ac-martin** [comment]
When we have client rendering enabled, we shouldn't need to re-load the page.

When it's only server-side rendered, it will need to load a new page.

As long as we run everything though GET variables, (which we can access with the `useLocation` hook) it should all work.

See: https://github.com/daniel-ac-martin/NotGovUK/blob/master/apps/govuk-template/src/common/pages/result.tsx#L8

**Comment by MikeDThorpe** [comment]
A new branch - [pagination-redesign](https://github.com/UKHomeOffice/design-system/tree/pagination-redesign) - has been opened for this issue.

**Comment by daniel-ac-martin** [comment]
Thanks @MikeDThorpe.
Once there's something to show, it would be worth opening a draft PR. That way we can see a preview.
