### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#35]
Switching between views of grouped content; hiding content that doesn’t always need to be visible.

https://home-office-digital-patterns.herokuapp.com/patterns/tabs

**Comment by chris-hanson-hoddat** [comment]
I've done some work on the horizontal tabs
https://github.com/UKHomeOffice/home-office-design-system/tree/tabs-update

**Comment by karypun** [comment]
Outdated issue.
