### ISSUE TITLE
Multiple loops

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#36]
Multiple loops lets users quickly add more data, for example adding multiple people to one visa application.  

## Examples  

![multiple-loop](https://user-images.githubusercontent.com/13904084/30319843-defc7fd0-97a8-11e7-8140-54249fee1400.png)

![screen_shot_2017-06-06_at_08 03 07](https://user-images.githubusercontent.com/13904084/30319870-f23c5a5c-97a8-11e7-8e10-c8b006da73be.png)

**Comment by helenadt** [comment]
![book-travel-people-page](https://user-images.githubusercontent.com/25151199/32659787-2f4ad322-c618-11e7-90e5-dee5fe64e909.png)

Example from 'Book travel in and out of the UK'

**Comment by SueSpevack** [comment]
Closing this issue as it currently exists in the design system. Raise a new issue if needed.

**Comment by kelliedesigner** [comment]
MOJ have published a new pattern called 'Add to a list':
https://design-patterns.service.justice.gov.uk/patterns/add-to-a-list/

Comments and feedback can be made on the GitHub Discussion:
https://github.com/ministryofjustice/moj-frontend/discussions/203
