### ISSUE TITLE
Case summary

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#37]
A summary of a case for a case-working system

## Examples  

<img width="1076" alt="syriacase 1" src="https://user-images.githubusercontent.com/13904084/30320902-0c2312e6-97ac-11e7-8796-3551886ce953.png">
  
![sponsorship_case_summary](https://user-images.githubusercontent.com/13904084/30320915-1519b454-97ac-11e7-96f0-5ded8330984b.png)

**Comment by SueSpevack** [comment]
Closing this issue as it currently exists in GOV: https://design-system.service.gov.uk/components/summary-list/. Raise a new issue if needed.

**Comment by matthew20177** [comment]
Hey I

**Comment by matthew20177** [comment]
Uuuu
