### ISSUE TITLE
Search pagination

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#38]
## Description  
A control that allows you to navigate through multiple pages of search results

## Why you need a new pattern  
This has been seen in a few internal services and I think we will need to look at a way to standardise it. Not currently a GDS pattern.

## Examples  
![sip_desktop](https://user-images.githubusercontent.com/13904084/30321148-f22a89d6-97ac-11e7-9419-4c339baf2ee3.png)  

<img width="427" alt="screen_shot_2017-07-10_at_15 14 48" src="https://user-images.githubusercontent.com/13904084/30321151-f33aa8f6-97ac-11e7-979a-6b0f20545616.png">

**Comment by andrewscrivener** [comment]
￼<img width="1005" alt="pagination" src="https://user-images.githubusercontent.com/1358700/34247723-6da515f0-e62b-11e7-9727-36edc4272030.png">

This is the version I've used on a couple of projects. From testing during the HOCS project users asked us to add the ability to jump to the last page as well as viewing everything if they wanted. It's not the most minimal example but provided all of the functionality users from different teams required.

**Comment by SueSpevack** [comment]
Closing this issue as it currently exists in the design system: https://design.homeoffice.gov.uk/components/pagination. 
Raise a new issue if needed.
