### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#39]
https://home-office-digital-patterns.herokuapp.com/icons

**Comment by owenm6** [comment]
We need better instructions so people can use the icons on their prototypes

**Comment by owenm6** [comment]
Instructions updated to include how to use in the kit commit #28ea265421615970050a28347117cd347e59c885

**Comment by joelanman** [comment]
it would be really useful to know which services use these icons, screenshots would be awesome.

**Comment by eliothill** [comment]
There's two internal service that are using these icons, will reach out to the designers to see if we can add screengrabs. We've begun interspersing examples of the icons like the [back button(https://github.com/UKHomeOffice/design-system/issues/95)

Also worth reading this blog – the idea being if we don't say anything, teams will do whatever they like.
[Good icons should be invisible](https://hodigital.blog.gov.uk/2017/08/18/good-icons-should-be-invisible/)

**Comment by SueSpevack** [comment]
Closing and moving this issue to here: https://github.com/UKHomeOffice/design-system/issues/155
