### ISSUE TITLE
Add posters to the inclusive language guidance page + update content

### ISSUE THREAD

**Issue by Sarraounia** [UKHomeOffice/design-system#405]
New content for posters to be added to the existing [Inclusive Language guidance](https://design.homeoffice.gov.uk/accessibility/inclusive-language). 

A new section of content to be placed, at the bottom of the screen, above the 'Get in touch' box. The PDFs will be directly attached and downloadable from the link - is this possible?

**Still awaiting final sign-off on the posters for publication. When I have this (expected soon), I will upload the posters to this issue.** 

![Screenshot 2022-07-08 at 12 18 28](https://user-images.githubusercontent.com/43995815/179188050-d1e22e58-798c-4e49-afc7-96249409fb3c.png)

**Comment by Sarraounia** [comment]
[Draft pull request 464](https://github.com/UKHomeOffice/design-system/pull/464)) created in readiness for publication of posters on HO posters GitHub.

**Comment by daniel-ac-martin** [comment]
@Sarraounia: Can we close this now?

**Comment by Sarraounia** [comment]
> 

Yes @daniel-ac-martin - happy to close this now.
