### ISSUE TITLE
Highlighting

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#41]
A way to highlight data matches. It helps users easily see matches.

https://home-office-digital-patterns.herokuapp.com/patterns/highlighting-matches  
  
![screen_shot_2017-04-18_at_09 05 35](https://user-images.githubusercontent.com/13904084/30324359-ada644a6-97b8-11e7-8742-f1400cb86258.png)

**Comment by peteryates** [comment]
This is a really interesting addition. Is there any reason you've opted to use `<span class="highlight">...</span>` over [`<mark>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark)?

**Comment by joeedhorton** [comment]
Closing this issue as it currently exists in the [design system](https://design.homeoffice.gov.uk/components/highlighting-matches). 

Raise a new issue if needed.

**Comment by isobelseacombe** [comment]
I've noticed that this isn't accessible via the menu of components in the design system - is it possible to add it to the menu?
