### ISSUE TITLE
Table multi-select

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#42]
Gives users the ability to select multiple table rows

## Example  

![clickable_row](https://user-images.githubusercontent.com/13904084/30324418-e4c6799c-97b8-11e7-8954-77be19aa7f54.gif)

**Comment by joeedhorton** [comment]
Closing this issue as it currently exists in the [design system](https://design.homeoffice.gov.uk/components/table-multiselect). 

Raise a new issue if needed
