### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#43]
A way to tag elements by commonly grouped or related items.

**Comment by RossGower** [comment]
I've designed this...



Which uses the labels component https://home-office-digital-patterns.herokuapp.com/components/labels as its base and used the accessible colour scheme Background: #CBCBCB Foreground: #0B0C0C  from https://home-office-digital-patterns.herokuapp.com/styles/colour

![image](https://user-images.githubusercontent.com/49675949/61127408-1debd800-a4a7-11e9-93df-97e80dee5b79.png)

![image](https://user-images.githubusercontent.com/49675949/61127440-33610200-a4a7-11e9-8fcb-dcc479740322.png)

Our developer has then taken the code from the labels component, but the label uses a colour combination outside of our accessible colour palette

![image](https://user-images.githubusercontent.com/49675949/61127377-06acea80-a4a7-11e9-8f40-11e29f26c908.png)

While the label used to label the example is from our accessible colour palette. So theres a bit of an inconsistency there.

Could the labels be changed to include both the Black text on light grey and white text on dark grey combinations from our colour palette?

**Comment by joeedhorton** [comment]
Closing this issue as it currently exists in the [design system](https://design.homeoffice.gov.uk/components/labels). 

Raise a new issue if needed

**Comment by joeedhorton** [comment]
It seems we've gone for lowercase as apposed to NHS and GOV. Would be good to do/see some research around what's the easiest/quickest to read

**Comment by isobelseacombe** [comment]
> It seems we've gone for lowercase as apposed to NHS and GOV. Would be good to do/see some research around what's the easiest/quickest to read

NHS are using sentence case and it seems to have tested well https://service-manual.nhs.uk/design-system/components/tag

**Comment by joeedhorton** [comment]
I think their approach is good. All lowercase looks very odd to me

**Comment by karypun** [comment]
I agree, the labels need to be reviewed, partly as to whether we still refer to them as labels (NHS, GOV.UK and other systems refer to them as tags). Would any designers like to share examples of this?
- what do you call them (labels, badges, tags)?
- what is the context/application in which you use them (header, table, etc)
- any research/accessibility behind it?

**Comment by isobelseacombe** [comment]
![Tags](https://user-images.githubusercontent.com/43995752/116562566-2c64e700-a8fb-11eb-8ddf-ad009ce8c638.png)

I've done a bit of comparison of the different tags that are in use in gov and NHS. The rules for usage from the NHS are pretty sound so I've been following them. https://service-manual.nhs.uk/design-system/components/tag

**Thoughts on the differences in design:**
In terms of contrast against the grey background, the ones with the stroke around them are much more visible. 

The boxes around the gov ones are quite large - so when using them in tables (like the example Ross shared above) they could do with being a bit smaller.  

Use cases for them so far:

Using them to show a binary status of a thing: 
- a report being complete/incomplete 
- an item of reference data showing as active/inactive

Multiple statuses that change over a period of time - to show when a record is coming towards its expiry date and requires action to be taken. 

<img width="486" alt="status tags in a table" src="https://user-images.githubusercontent.com/43995752/116564207-aba6ea80-a8fc-11eb-88cf-32153cbafd2f.png">

Obviously we shouldn't rely on colour as the only way of displaying information - but it does help to support the understanding of the status. In this case (screenshot above) it was noted in usability testing that the user liked the 'traffic light' colours for each of the statuses and it helped them to understand which one to action first. This is something that has come up in previous policing projects and seems to be a theme used across other police IT.

**Comment by karypun** [comment]
@isobelseacombe  These have been used in Animal science licensing against the HO styles with grey background. Would be good to get in touch with their team to find how it tested.

<img width="635" alt="Screenshot 2021-06-24 at 08 18 59" src="https://user-images.githubusercontent.com/13965310/123219591-f8560e80-d4c4-11eb-8bf7-640bbf2f5788.png">

**Comment by daniel-ac-martin** [comment]
Is this sufficiently covered by https://design-system.service.gov.uk/components/tag/ ?
