### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#45]
Subnavigation that appear below the service header  

https://design.homeoffice.gov.uk/components/navigation

**Comment by catrionabudge** [comment]
https://design.homeoffice.gov.uk/components/navigation

**Comment by catrionabudge** [comment]
Switched tag round, as this is listed under components in the design system

**Comment by joeedhorton** [comment]
Closing this issue as it currently exists in the [design system](https://design.homeoffice.gov.uk/components/navigation). 

Raise a new issue if needed
