### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#46]
Time-ordered activity showing the history of a person or object with additional context.  

https://design.homeoffice.gov.uk/components/timeline

**Comment by owenm6** [comment]
Changes to make the styling consistent between public and caseworking services 1f88984a2a99d601382b1f7620970b05f8ef6d22

**Comment by joeedhorton** [comment]
Ross and I will take this one forward; collect research and decide the next steps
