### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#48]
Smaller checkboxes for internal services where the GOV.UK standard is not appropriate.  

https://home-office-digital-patterns.herokuapp.com/components/checkboxes

**Comment by owenm6** [comment]
Bug reported by @karypun https://github.com/UKHomeOffice/design-system/issues/98

**Comment by owenm6** [comment]
Increased the spacing between elements b474265e739c12c1307ae9713d3ed0456f1d30fc

**Comment by karypun** [comment]
Closing this as this is now on GDS design system
