### ISSUE TITLE
Continuous integration tests broken in Node.js v18

### ISSUE THREAD

**Issue by tomyems** [UKHomeOffice/design-system#492]
In the change from Node.js 16 to 18, the '.toLocaleTimeString' function now returns a character with ASCII code '8239' between the time and the 'am' or 'pm'.

This has broken our tests because the time component removes the space (with ASCII code '32').

**Comment by robertdeniszczyc2** [comment]
I think this issue can be closed as appears to be resolved by https://github.com/UKHomeOffice/design-system/pull/493
