### ISSUE TITLE
New component: loading spinner

### ISSUE THREAD

**Issue by tomyems** [UKHomeOffice/design-system#494]
Create a new component based from discussion https://github.com/UKHomeOffice/design-system/discussions/488.

For the input text 'Loading the next task for this case', the desired output HTML is:
```
<div class="govuk-grid-row">
    <div class="govuk-!-padding-bottom-9"></div>
    <div class="govuk-!-padding-bottom-9"></div>
    <div class="loading" style="margin-left:auto; margin-right: auto" aria-live="polite" role="status"></div>
</div>

<div class="govuk-!-padding-bottom-7"></div>

<div class="govuk-grid-row">
    <h1 class="govuk-heading-m" style="text-align: center">Loading the next task for this case</h1>
    <div class="govuk-!-padding-bottom-9"></div>
    <div class="govuk-!-padding-bottom-9"></div>
</div>
```

So the only variable is the text in the `<h1>` tags.

With the css styling:
```
.loading {
 border: 12px solid #DEE0E2;
 border-radius: 50%;
 border-top-color: #005EA5;
 width: 80px;
 height: 80px;
 -webkit-animation: spin 2s linear infinite;
 animation: spin 2s linear infinite;
}
@-webkit-keyframes spin {
 0% { -webkit-transform: rotate(0deg); }
 100% { -webkit-transform: rotate(360deg); }
}
@keyframes spin {
 0% { transform: rotate(0deg); }
 100% { transform: rotate(360deg); }
}
```

**Comment by tomyems** [comment]
We can decide whether you want to include the 'timeout error' if it's been loading too long in the component itself or in the guidance (whichever is best from a technical point of view)

**Comment by MikeDThorpe** [comment]
@tomyems - is a H1 semantically the correct tag to be using for the text?

**Comment by MikeDThorpe** [comment]
@tomyems - i think the html in the desired example needs looking at again as there are mismatching/incomplete tags

**Comment by tomyems** [comment]
> @tomyems - i think the html in the desired example needs looking at again as there are mismatching/incomplete tags

Fixed now Mike, I should say that's possibly not the best way of doing it, perhaps the padding should be in the css rather than in those extra divs ....

**Comment by tomyems** [comment]
https://63fcab113b69be07fd6c00aa--hods.netlify.app/components?name=Loading%20spinner
