### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#50]
Help overlays containing contextual help content for complex interactions

**Comment by davehaigh** [comment]
small point - you reference service point 12 (make it simple to use) - but that it is **now service point 4** in the new service standards

**Comment by joeedhorton** [comment]
Closing this issue as it currently exists in the [design system](https://design.homeoffice.gov.uk/patterns/get-more-details). 

Raise a new issue if needed.
