### ISSUE TITLE
Interruption card

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#51]
Interrupt the user flow with important information. Must be acknowledged before continuing.

**Comment by catrionabudge** [comment]
Relevant issue in gov.uk backlog https://github.com/alphagov/govuk-design-system-backlog/issues/27

**Comment by joeedhorton** [comment]
Closing this issue as it currently exists in the [design system](https://design.homeoffice.gov.uk/patterns/stop-and-think). 

Raise a new issue if needed.
