### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#52]
A familiar landmark at the top of a page.

**Comment by helenadt** [comment]
What is the ‘Digital by default’ logo?

**Comment by helenadt** [comment]
For internal services I have noticed that a couple have moved the phase tag to the header. I was thinking of doing the same. What are people's thoughts?

**Comment by owenm6** [comment]
I'm not sure of what the 'Digital by default' logo is. The phase tag works well in the header. I will add that to the guidance.

**Comment by hvekriya** [comment]
Hi,
I am using this pattern for an internal service.
https://gov-ho-idp-prototype.herokuapp.com/v12/search?
Any feedback on the use of it?
It would be good if it was added to your list of services using the pattern :)

**Comment by christaylor-hod** [comment]
Hi @hvekriya - can you get in touch with me via chris.taylor@digital.homeoffice.gov.uk - I'd like to know more about your project, thanks

**Comment by owenm6** [comment]
@hvekriya Thanks for letting us know you are using the header pattern. Interested to know if you've any research on the mobile view and shortening the service name? We would generally avoid this if possible.

I've added your service to the page.

**Comment by hvekriya** [comment]
@owenm6 our service is not really used on mobile devices. However, I added that in as a safe option if someone was to resize the window in chrome to a smaller view. So far feedback for it has been really positive. Thanks for adding it on the page :)

**Comment by joeedhorton** [comment]
Joe and Ross will take this one forward; collect research and decide the next steps

**Comment by joeedhorton** [comment]
Closing this issue as it currently exists in the [design system](https://design.homeoffice.gov.uk/styles/templates). 

Raise a new issue if needed
