### ISSUE TITLE
Status indicator

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#53]
A way to show a status on a case. The smaller text can show the info needed for the next action, in this case it's the date for next review.  

![status_banner](https://user-images.githubusercontent.com/13904084/30327973-e4b785f6-97c5-11e7-8a40-c0ccc4a7ace6.png)

**Comment by samwake** [comment]
![statuses](https://user-images.githubusercontent.com/19802499/31076783-cbc2a248-a773-11e7-8869-1c4810beb8d5.png)

Another example - this is a three-step status indicator in use on SIP.

**Comment by helenadt** [comment]
![image](https://user-images.githubusercontent.com/25151199/32650947-97ce8f54-c5f7-11e7-9a56-6b255deedf6a.png)
An example from the 'Book travel in and out of the UK' internal service

**Comment by owenm6** [comment]
@samwake @helenadt Do you have any user research around these statuses?

**Comment by samwake** [comment]
I think the first, blue, one was part of sponsorship which didn't get as far as testing. The Complied status is SIP and I don't know of anything specific but will ask Ben.

**Comment by owenm6** [comment]
@samwake My thinking was a more common case for a status is when a user has to do something because of an action elsewhere. For this something more prominent makes sense. But there is a second need for a less prominent status when the user doesn't need to take action but wants to stay informed like in your report status.

**Comment by owenm6** [comment]
An example of status messages (and alerts) from DWP - https://dwp-patterns.herokuapp.com/alerts

**Comment by joeedhorton** [comment]
Closing and moving this issue to [here](https://github.com/UKHomeOffice/design-system/issues/157).
