### ISSUE TITLE
Performance page 

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#64]
A place to collect data on what services are consuming the patterns and components

**Comment by eliothill** [comment]
We should use/consider the [mandatory KPIs of GOV.UK](https://www.gov.uk/performance) when measuring the design system. But will also look into other ways of reporting value and uptake.

**Comment by owenm6** [comment]
Should we add a feedback link?

**Comment by eliothill** [comment]
I thought we had links on each page to comments/issues in github? Are you thinking of the 'Is this page useful?' [Like the footer page here](https://www.gov.uk/service-manual/service-standard) to measure binary value of 'Yes/No'?
