### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#80]
Filtering content and data

**Comment by samwake** [comment]
![filters](https://user-images.githubusercontent.com/19802499/31442496-8810c0e4-ae8e-11e7-825d-b4891fb72ddd.gif)

These categories of things are not mutually exclusive.

**Comment by owenm6** [comment]
We could recommend starting points for both filtering one thing at a time and filtering on multiple things

**Comment by megandrodger** [comment]
The refugee resettlement service is looking at how to filter cases by various different variables to fit a certain criteria (for a property or flight)

**Comment by jimkosem-hod** [comment]
Going to be looking at this while Michael is away

**Comment by jimkosem-hod** [comment]
@megandrodger Do you have any examples so far? It would be good to take a look at what you have or what you were thinking of so we can start putting this page together.

**Comment by jimkosem-hod** [comment]
There seems to be essentially two slightly incompatible ways of filtering, vertical and horizontal.
[](https://paper.dropbox.com/doc/Search-filters-VxP46U2qgjrYnNwqXakKJ)

The vertical filtering seems to be less overwhelming in terms of showing options and showing order of options which the horizontal mode combines into long, multi-choice interactions. It also avoids falling into using tabs which should be navigational.

This could be aided by though by combining sorting into the same pattern. So that means that a left hand vertical filtering is done by the user to lessen or focus the amount of information they see and then provide controls horizontally to filter those results.

**Comment by karypun** [comment]
In IE Business Rules, we're currently looking to A/B test the filters in both horizontal and vertical formats. Depending on the choice of components, this could impact the format as we're now considering replacing one of the drop downs with checkboxes which makes the vertical format a better choice to work with. 
[01 SEARCH CASES.pdf](https://github.com/UKHomeOffice/design-system/files/1575451/01.SEARCH.CASES.pdf)
[01 SEARCH CASES 2.pdf](https://github.com/UKHomeOffice/design-system/files/1575452/01.SEARCH.CASES.2.pdf)

**Comment by jimkosem-hod** [comment]
@karypun Do you have the Sketch files for the second vertical one?

**Comment by karypun** [comment]
@jimkosem-hod it's attached
[iebr-wireframes-v01.2.zip](https://github.com/UKHomeOffice/design-system/files/1576275/iebr-wireframes-v01.2.zip)

**Comment by hom-bahrani** [comment]
@samwake I'm interested in creating this table, do you have any code / styles for it?

**Comment by samwake** [comment]
@hom-bahrani Sorry, no I don't have the code for that example I showed. It started out as a GOV.UK table as here https://govuk-elements.herokuapp.com/data/ and has had changes from there.

**Comment by hom-bahrani** [comment]
@samwake no worries, I'll have a crack at it using your design

**Comment by RossGower** [comment]
Hi @samwake did you ever progress with tag based filtering? If so, do you have much user research on its effectiveness, issues etc.?

**Comment by samwake** [comment]
@RossGower I'm not sure where it got to I'm afraid - I moved off the project. I think it was implemented, but I've not been able to work out who is on that project to hear any findings at the moment.

**Comment by joeedhorton** [comment]
Closing and moving this issue to [here](https://github.com/UKHomeOffice/design-system/issues/159).
