### ISSUE TITLE
Postcode lookup

### ISSUE THREAD

**Issue by karypun** [UKHomeOffice/design-system#84]
Different sorts of postcode lookups across gov. Looking at one we've customised through research to include the option of adding the address manually on the first step instead of the second step if the postcode isn't found. We found this to be a common issue with lots of new builds in landlord checking services.

![postcode-lookup](https://user-images.githubusercontent.com/13965310/32329917-53ab930c-bfd6-11e7-8cc6-e04815e7d02c.png)

**Comment by owenm6** [comment]
Added at https://home-office-digital-patterns.herokuapp.com/patterns/postcode

**Comment by karypun** [comment]
Closing outdated issue.
