### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by helenadt** [UKHomeOffice/design-system#86]
Provide information about how internal users can seek help if they encounter a problem.

## Example
![book-travel-support-design](https://user-images.githubusercontent.com/25151199/32845423-8d2b40fa-ca1c-11e7-99a8-85ae14995de2.png)

**Comment by owenm6** [comment]
@helenadt How does a user get to this page? Is it an error page or is there a feedback link somewhere?

**Comment by owenm6** [comment]
Guidance here - https://home-office-digital-patterns.herokuapp.com/patterns/support

**Comment by helenadt** [comment]
![report-a-problem-update](https://user-images.githubusercontent.com/25151199/34106559-8f22cb56-e3f0-11e7-9bed-cb97182d0ae3.png)

Sorry @owenm6 I didn't see your comment. We have a link in our footer for now. We have also provided some prompts now, the user enters the problem and it is sent to the service desk rather than them having to say which service they are using etc.
