### ISSUE TITLE
Confirmation pages

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#90]
Different confirmation pages based on different scenarios.

https://home-office-digital-patterns.herokuapp.com/components/confirm-pages

**Comment by simon-castillo** [comment]
On access needs research, two visually impaired users found the white text on dark green background difficult to read - one was using a high-contrast mode already. Maybe this is a reason why the GDS pattern is lighter? The other user admitted there are a lot of different colour preferences, but flagging in case the same problem comes up elsewhere.

**Comment by owenm6** [comment]
@helenadt Hi Helena. The lighter green used across Government isn't accessible if the confirmation text is 19px. It fails on colour contrast. So that was the reason for the change.

**Comment by helenadt** [comment]
@owenm6 ok thanks!

**Comment by martinwake** [comment]
Hi folks: there's a typo in the "Request received" example. "...and its current status" should *not* have an apostrophe in "it's".

![image](https://user-images.githubusercontent.com/26182217/71012982-db7a9700-20e7-11ea-87da-557e684aca37.png)
