### ISSUE TITLE
Using images as guidance

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#92]
Using images to visually explain things to users like where to find a reference or what a URL is.

**Comment by owenm6** [comment]
Example from a service @karypun worked on. They found in testing that not everyone was familiar with URL or web link; tried other things like providing hint text alone or a progressive reveal but this tested extremely well with all users This <img width="990" alt="screen shot 2018-01-31 at 17 50 59" src="https://user-images.githubusercontent.com/13904084/35673846-92109d94-073a-11e8-9d52-507a1f6ba3df.png">

**Comment by christaylor-hod** [comment]
Probably need to consider under what circumstances to start with a photo of the thing you're trying to point out and when to use a more abstract image. Would be good to collect some examples of this from across the Home Office and set some visual standards and guides (maybe Sue can help with this?)

**Comment by owenm6** [comment]
<img width="941" alt="screen shot 2018-08-20 at 09 29 29" src="https://user-images.githubusercontent.com/13904084/44329150-9abf2f00-a45b-11e8-93f4-1d475bd8986f.png">

**Comment by owenm6** [comment]
<img width="736" alt="screen shot 2018-08-20 at 09 31 22" src="https://user-images.githubusercontent.com/13904084/44329242-d954e980-a45b-11e8-983b-39423b3d0e89.png">

From DVLA vehicle tax check service

**Comment by owenm6** [comment]
Guidance published - https://home-office-digital-patterns.herokuapp.com/patterns/image-guidance

**Comment by karypun** [comment]
Closing this issue as it currently exists in the design system: https://design.homeoffice.gov.uk/patterns/find-information-on-a-document
Raise a new issue if needed.
