### ISSUE TITLE
Back link

### ISSUE THREAD

**Issue by eliothill** [UKHomeOffice/design-system#95]
Have experienced multiple research participants not notice/understand the 'back button' in the context of the form, when needing to correct an error on a previous page.

Users are less inclined to use the browser back button in case it takes them away from the form (assume from previous experience of single page applications).

Suggest making text more descriptive, increase space and make use of icons consistent.

**Comment by eliothill** [comment]
<img width="259" alt="suggested-update" src="https://user-images.githubusercontent.com/6698288/34110538-e49fe524-e3fe-11e7-96ee-137b564481e0.png">
<img width="196" alt="arrow-on-other-nav" src="https://user-images.githubusercontent.com/6698288/34110540-e4bbd13a-e3fe-11e7-8cab-087e939c6bff.png">
<img width="240" alt="arrow-on-miller-column-nav" src="https://user-images.githubusercontent.com/6698288/34110541-e4d259fa-e3fe-11e7-8517-979be391403f.png">
<img width="342" alt="details-progressive-disclosure" src="https://user-images.githubusercontent.com/6698288/34110542-e4ed9792-e3fe-11e7-9bfc-6a20489d09dd.png">
<img width="236" alt="current-back" src="https://user-images.githubusercontent.com/6698288/34110543-e52c5f04-e3fe-11e7-8fba-f920f1a4b040.png">
<img width="277" alt="example-1-taken-for-usability-test" src="https://user-images.githubusercontent.com/6698288/34110544-e5634a64-e3fe-11e7-992c-dde4b8b09504.png">

**Comment by jimkosem-hod** [comment]
Have actually seen it used in testing a couple of times. Can't give you exact figures though.

**Comment by owenm6** [comment]
Feedback from Megan: fear from some users that the back button would undo work. Users weren't sure where the back button would take them.

**Comment by jimkosem-hod** [comment]
Fair point. It could go both ways really. I think in terms of anything you need to submit it might be best avoided, but if it was anything that is more informational or navigational, then I would think its fine.

**Comment by owenm6** [comment]
Added the component - https://home-office-digital-patterns.herokuapp.com/components/back

**Comment by karypun** [comment]
Closing this issue as it currently exists in the design system. Raise a new issue if needed

**Comment by isobelseacombe** [comment]
Been doing lots of thinking about this in PPPT lately. Have come up with rules for using back links in lateral task flows and breadcrumbs for app navigation. Sharing work with colleagues in BICS then will share here

**Comment by chris-barrett-ddts** [comment]
> Been doing lots of thinking about this in PPPT lately. Have come up with rules for using back links in lateral task flows and breadcrumbs for app navigation. Sharing work with colleagues in BICS then will share here

We're having similar thoughts on WRLS at the moment and just wondering how this was implemented on your service and what the outcomes were? Thanks
