### ISSUE TITLE
Signing out

### ISSUE THREAD

**Issue by jimkosem-hod** [UKHomeOffice/design-system#96]
When a user needs to view a secure page, such as visa information, for which they need to login, we need a pattern to handle logging out of that secure view.

![unknown](https://user-images.githubusercontent.com/33902119/34205754-940da10e-e57b-11e7-84dc-0ea8498a2bd4.png)

One way of doing that is putting the sign out on the same bar as the beta badge.

**Comment by jimkosem-hod** [comment]
@eliothill ECS has tested this pattern right?

**Comment by eliothill** [comment]
@jimkosem-hod we're researching this at the moment, that's similar to one approach. There is a pattern for [sub navigation](https://home-office-digital-patterns.herokuapp.com/components/navigation) and the content around sign out/log out/leave session will be dependant on the service and how user's describe the action.

Example of same approach elsewhere on GOV.UK
<img width="512" alt="driving-licence-link" src="https://user-images.githubusercontent.com/6698288/34218522-4e9c86fa-e5a6-11e7-8198-68d10f020067.png">

**Comment by eliothill** [comment]
Also an example from [HMRC's Account header](http://hmrc.github.io/assets-frontend/components/account-header/index.html), where possible we should provide consistency with other depts before creating new patterns.

**Comment by jimkosem-hod** [comment]
@eliothill @owenm6 I think we could then say that sign out would be the same as navigation? And then we incorporate the HMRC one as Eliot pointed to?

**Comment by helenadt** [comment]
This could also include what is displayed when you sign out.
![image](https://user-images.githubusercontent.com/25151199/34678372-e168d996-f48a-11e7-82d8-0f738c38928a.png)

**Comment by owenm6** [comment]
@jimkosem-hod We need to consider our service header as that is currently where we recommend people put the sign-out link - https://home-office-digital-patterns.herokuapp.com/patterns/header

**Comment by eliothill** [comment]
@owenm6 this is more applicable for @helenadt as her service is an internal one? @jimkosem-hod project is public facing. I don't think there's an issue differentiating navigation on internal/external but should probs be consistent if it's one or the other.

**Comment by owenm6** [comment]
That is true. Feels like there are still things to consider...

**Comment by helenadt** [comment]
I am not sure having the link in the phase banner is appropriate for internal services as there still needs to be a decision on whether internal services have a banner.  Notify and Pay don't have one but instead have the phase tag next to the service name in the header.

**Comment by helenadt** [comment]
DWP also have examples of a 'utility' type bar https://dwp-patterns.herokuapp.com/adminmenus

**Comment by eliothill** [comment]
Notify _et al_ use the utility bar as well as adjusting the service header and additional header navigation 🙃

<img width="969" alt="screen shot 2018-01-09 at 16 07 18" src="https://user-images.githubusercontent.com/6698288/34730415-4709e89a-f557-11e7-8738-a1212f50dc33.png">

**Comment by atrvrs** [comment]
This is a great discussion. A few questions: 

1. is it possible that there some different use cases in here that _might_ need more than one pattern. For example, there's a sign out on an banking site and on, say, a supermarket. I know I *need* to sign out of one, *should* sign out of the other. Might that influence what pattern/placement/treatment feels appropriate? (Jim's example feels like the former)

2. Are there differences in what might be appropriate for a single use, public-facing service and a heavy repeat-use expert-user admin interface.

3. anything that involves using the utility bar or service header gets into trad blind spots for users. It's worth us making sure, in research, that where the user *needs* to sign out at the end of a task (i.e. signing out is effectively part of that task) that we're factoring that into research plans, making sure users can do so unprompted, with confidence etc

Last thing: this might be a case where consistency in content design might just be more important than design treatment...

**Comment by simon-castillo** [comment]
On right to work we've named it 'Finish and leave service' as users didn't feel as though they'd signed in to anything. The three locations we're using are:

**Phase banner:**

![image](https://user-images.githubusercontent.com/24433505/35738418-ba909bc4-0826-11e8-915a-a5cb912be545.png)

**Primary button:**

![image](https://user-images.githubusercontent.com/24433505/35738436-d06198f4-0826-11e8-9cf1-b1cfa13c6afd.png)

**Secondary button:**

![image](https://user-images.githubusercontent.com/24433505/35738447-df0b9e5e-0826-11e8-91d5-25698245a341.png)

We'll definitely have it as a button at the end of each flow (as well as in the phase banner throughout) but questioning whether to have it as a secondary button on earlier pages.

Also agree that this is more suited to public facing services and 'sign out' in the very top right might be fine for internal users.

**Comment by owenm6** [comment]
@simon-castillo Did users use the link? Did they see any reason to leave the service or did they just close the browser down?

**Comment by simon-castillo** [comment]
@owenm6 We've seen them use the button at the end of the main journey, and also state that they would want to make sure they've securely left. We haven't observed anyone use the phase banner link - mainly because of the scenarios we've tested with - but it's also a requirement from security that they have the option to leave at any point once signed in.

**Comment by owenm6** [comment]
First iteration of guidance - https://home-office-digital-patterns.herokuapp.com/patterns/sign-out

**Comment by karypun** [comment]
Closing and moving this issue to here [#156](https://github.com/UKHomeOffice/design-system/issues/156)
