### ISSUE TITLE
Side tabs

### ISSUE THREAD

**Issue by owenm6** [UKHomeOffice/design-system#97]
This pattern is used widely across Home Office, particularly in caseworking systems.

**Comment by karypun** [comment]
We've just started using this for testing this week so will let you know the feedback for this.

**Comment by owenm6** [comment]
Published here - https://home-office-digital-patterns.herokuapp.com/components/side-tab

**Comment by karypun** [comment]
Closing this issue as it currently exists in the design system. Raise a new issue if needed.
