### ISSUE TITLE
Smaller checkboxes have a transparent background

### ISSUE THREAD

**Issue by karypun** [UKHomeOffice/design-system#98]
We've noticed that the smaller checkboxes and radio buttons have a transparent background when laid against coloured backgrounds. Would be good to make them white to promote better visibility.
<img width="1037" alt="screen shot 2018-01-22 at 15 11 44" src="https://user-images.githubusercontent.com/13965310/35228123-d895b2be-ff87-11e7-9196-00433c17e2c2.png">

**Comment by owenm6** [comment]
Moved to #48
